# Generated by Django 3.1.1 on 2020-09-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(default='null', max_length=50)),
                ('role', models.CharField(choices=[('OP', 'Operator'), ('SV', 'Supervisor')], default='SV', max_length=2)),
                ('department', models.CharField(default='null', max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('tg_user', models.CharField(default='null', max_length=20)),
            ],
        ),
    ]
