# Generated by Django 3.1.1 on 2020-09-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_user',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
