# Generated by Django 3.1.1 on 2020-09-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_auto_20200913_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('BS', 'BS'), ('Clicker', 'Clicker')], default='Clicker', max_length=20)),
                ('status', models.CharField(choices=[('Free', 'Free'), ('Busy', 'Busy')], default='Busy', max_length=20)),
            ],
        ),
    ]
