# Generated by Django 3.1.1 on 2020-09-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='Euro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20)),
                ('phone', models.IntegerField(default=0)),
                ('transport', models.CharField(choices=[('Viber', 'Viber'), ('Whatsapp', 'Whatsapp')], default='Whatsapp', max_length=20)),
                ('key', models.CharField(max_length=10)),
                ('device_owner', models.CharField(choices=[('We', 'We'), ('Client', 'Client')], default='Client', max_length=20)),
                ('stable_status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Lost_registration', 'Lost_registration')], default='Online', max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('company_id', models.IntegerField(default=1)),
                ('equipment_code', models.CharField(default='client', max_length=20)),
                ('partner_id', models.IntegerField(default=1, max_length=5)),
                ('status_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20)),
                ('phone', models.IntegerField(default=0)),
                ('transport', models.CharField(choices=[('Viber', 'Viber'), ('Whatsapp', 'Whatsapp')], default='Whatsapp', max_length=20)),
                ('key', models.CharField(max_length=10)),
                ('device_owner', models.CharField(choices=[('We', 'We'), ('Client', 'Client')], default='Client', max_length=20)),
                ('stable_status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Lost_registration', 'Lost_registration')], default='Online', max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('company_id', models.IntegerField(default=1)),
                ('equipment_code', models.CharField(default='client', max_length=20)),
                ('partner_id', models.IntegerField(default=1, max_length=5)),
                ('status_datetime', models.DateTimeField()),
            ],
        ),
    ]
