# Generated by Django 3.1.1 on 2020-09-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_auto_20200917_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ru',
            name='partner_id',
            field=models.IntegerField(default=1),
        ),
    ]
