# Generated by Django 3.1.1 on 2020-09-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0008_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='null', max_length=30)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(default='null', max_length=50)),
                ('role', models.CharField(choices=[('Operator', 'Operator'), ('Supervisor', 'Supervisor')], default='Supervisor', max_length=20)),
                ('department', models.CharField(default='null', max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('tg_user', models.CharField(default='null', max_length=30)),
                ('password', models.CharField(default='null', max_length=50)),
                ('date_last_update', models.DateTimeField()),
                ('avatar', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Free',
            new_name='Equipment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
