# Generated by Django 3.1.1 on 2020-09-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0009_auto_20200929_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='operator_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
